### ISSUE TITLE
Calendar jumps back to homeDate when it is out of view

### ISSUE THREAD

**Issue by drampelt** [Quivr/Android-Week-View#13]
First of all thank you for forking this project and merging some of the PRs that have been open for a while, I really appreciate it.

Since the min/max date feature was added, when the `homeDate` is out of view and you scroll vertically, sometimes the calendar will jump back so that the `homeDate` is in view again.

I spent a little while trying to figure out why today but haven't had any luck yet. I was hoping someone more familiar with the code might know what the issue could be.

I'll take a screen recording of the problem and upload that in a little bit.

**Comment by drampelt** [comment]
Here is a screen recording of the issue: https://drive.google.com/file/d/0BzW6GHHHAXgITF9HTW94cFQxVzQ/view?usp=sharing

As you can see when I go to before the `homeDate` and start scrolling up and down it sometimes jumps back. It seems to happen more rarely if you are after the `homeDate` but I have seen it occasionally.

**Comment by jhoobergs** [comment]
@drampelt It should be fixed. Thanks for reaching out.

**Comment by entropitor** [comment]
:raised_hands:

**Comment by drampelt** [comment]
Perfect, it is working great now. Thanks for the quick response!
