### ISSUE TITLE
How to add this fork to my project

### ISSUE THREAD

**Issue by jonathanballs** [Quivr/Android-Week-View#14]
I apologise if this is the wrong place to ask - it probably is - but how can I use this fork in my project? Do you guys just clone it and compile it on your machines. I've been trying for a few hours and can't work it out at all.

**Comment by jhoobergs** [comment]
In a few days or weeks, we will upload it to a maven repo so you can add it by adding 1 line in your build.gradle file.

For now you can try to add it as a git submodule to your project: https://git-scm.com/book/en/v2/Git-Tools-Submodules.

**Comment by jhoobergs** [comment]
@bonniejools You should be able to add it from gradle with 
`compile 'com.github.quivr:android-week-view:0.0.1-SNAPSHOT'`

**Comment by jonathanballs** [comment]
Ah you worked out how to fix the annotations build. I spent way too long trying to get that working to no avail. Thank you so much - you guys are the best! :smiley:
