### ISSUE TITLE
allDayEvents issue

### ISSUE THREAD

**Issue by alexandru1208** [Quivr/Android-Week-View#18]
When I put 2 or more AllDayEvents on one day, just one of them appears, but when i randomly tap on the calendar it changes with the second allDayEvent and if i randomly tap again it changes with first one and so on. I thought that multiple all day events should appear one after another just like normal events with same hour.

**Comment by jhoobergs** [comment]
![image](https://cloud.githubusercontent.com/assets/10081260/19960880/c5184bca-a1af-11e6-8ba6-3cf5cffada37.png)

@alexandru1208 Normally it should show the two or more events side by side as in the demo app.
