### ISSUE TITLE
start time and end time

### ISSUE THREAD

**Issue by masterofn1** [Quivr/Android-Week-View#19]
not a bug but a suggestion for improvement to allow visible start time and end time rather called time range? :-)

**Comment by masterofn1** [comment]
oops.. i think its the same as #11

**Comment by Sahara1990** [comment]
how i can fix this issue ?

**Comment by jhoobergs** [comment]
@khent04 You mean the possibility to set a range for start en end-time of the calendar ?

**Comment by jhoobergs** [comment]
@Sahara1990 You can always fork this repo, fix it and create a pull request to our repo.

**Comment by masterofn1** [comment]
Yep @jhoobergs ☺

**Comment by jhoobergs** [comment]
@khenix this feature has been added some time ago
