### ISSUE TITLE
Every event it's shown 3 times

### ISSUE THREAD

**Issue by aKuriel** [Quivr/Android-Week-View#20]
Like title says, every WeekViewEvent it's shown 3 times.

ussing:

Android OS: 6.0.1
Android Support: 24.1.1
Android Week View: 2.0.2

**Comment by jhoobergs** [comment]
@aKuriel This seems to be an error on your side. Does it also happen when you run the demo app ?

**Comment by masterofn1** [comment]
@aKuriel make sure to check if the events are already rendered. As per my checking onmontchangelistener is being called three times.

**Comment by jhoobergs** [comment]
it's always being called 3 times, for the period before the current period, for the current period and for the periode after the current period.

**Comment by entropitor** [comment]
@khent04 Check the documentation at https://github.com/alamkanak/Android-Week-View/blob/ed450d8c68a82fa176d37140880a6c921c98c521/library/src/main/java/com/alamkanak/weekview/MonthLoader.java#L41

**Comment by masterofn1** [comment]
Hi @caske33 , yeaps.. Thanks to that but i already checked that couple of weeks ago. I am just responding to issue.
Maybe we should address that to him ☺

**Comment by entropitor** [comment]
Oops, indeed, sorry!

@aKuriel: check my previous comment

**Comment by aKuriel** [comment]
i have this code:

```

        final List<WeekViewEvent> events = new ArrayList<>();
        Calendar calendarStart = Calendar.getInstance(Locale.US);
        Calendar calendar = Calendar.getInstance(Locale.US);
        calendarStart.add(Calendar.HOUR_OF_DAY, -5);
        events.add(new WeekViewEvent(1, "Evento 1", calendarStart, calendar));

        // wvEventos is the WeekView
        wvEventos.setMonthChangeListener(new MonthLoader.MonthChangeListener() {
              @Override
              public List<? extends WeekViewEvent> onMonthChange(int newYear, int newMonth) {
                      return events;
              }
         });
```

As you can see events list is initialized out of onMonthChange interface, but still adding events 3 times to view.

**Comment by jhoobergs** [comment]
@aKuriel See the link caske posted above: https://github.com/alamkanak/Android-Week-View/blob/ed450d8c68a82fa176d37140880a6c921c98c521/library/src/main/java/com/alamkanak/weekview/MonthLoader.java#L41

You should only return the events that are part of the period, but you always return the same list and because the MonthChangeListener.onMonthChange() is always called 3 times (as documented in the link above), your events are added 3 times.

**Comment by aKuriel** [comment]
should to be a filter in the api side, something like:

```
if(events are not for this month){
    // dont add to calendar.
}
```

or

```
if(id of event already exists){
  // override event or skip adding event
}
```

a common use case it's to load first the whole events list, for example a query:

SELECT \* FROM EVENTS WHERE BETWEEN start AND end;

with the current api we have to handle every interface method call:

```
if(myListItems are from this month){
 add event to list return;
}
```

to much work for something that should to be skipped.

or maybe i have not understanding the right implementation of this method, could you sir, please, explain me? i'm new with this api and excuse me if i don't understand so fast.

**Comment by jhoobergs** [comment]
@aKuriel The query you should use would be `SELECT * FROM EVENT WHERE BETWEEN startOfTheMonth AND endOfTheMonth`. This would solve your problem. This is not something the library should do, the library asks which events to draw for a certain month, then you have to return only the events of that month.

**Comment by aKuriel** [comment]
sure, we can do it in the api user side, i just giving my opinion, we can skip this validation part of previous current and next month, for a more comfortable use of api, you guys are doing a very good work, we are gonna be happy if your team can consider my suggest. 
Regards.

**Comment by jhoobergs** [comment]
@aKuriel This monthLoader is used for efficiency, events are only loaded when the user is actually looking at a date near the date of the event. 

So i'm afraid we won't implement your suggestion.

**Comment by aKuriel** [comment]
just another opinion: this init way is ugly. thanks.
