### ISSUE TITLE
Scrolling sluggish

### ISSUE THREAD

**Issue by ghost** [Quivr/Android-Week-View#22]
I've noticed that ever since I upgraded from the original WeekView to this fork that scrolling seems a bit off, for lack of a better word. If you move your finger to scroll in any direction it almost seems to ignore the touch for about half a second before it actually starts scrolling. If you hold your finger on the screen for like half a second however, scrolling will work just fine.

**Comment by jhoobergs** [comment]
@Menthuss Maybe it's because of the `scrollDuration` attribute, the default value at the original weekview was 500, and I don't know exactly why, but in this fork the default value is 250. Does it feel better when you set the scrollDuraction to 500 with the setter or xml attribute ?

**Comment by ghost** [comment]
Setting scrollDuration to 500 makes scrolling feel much more responsive, yes. There's still a tiny bit of delay before scrolling starts but it is much less noticeable now.
