### ISSUE TITLE
Event color bug

### ISSUE THREAD

**Issue by ghost** [Quivr/Android-Week-View#23]
I'm trying to give certain events different colors but I'm getting some odd results. I'm setting the color like this:

`if(res.getReservedForId() != userID){
                            event.setColor(android.R.color.holo_orange_light);
                        }else{
                            event.setColor(R.color.md_blue_500);
                        }`

The events are supposed to be orange and blue but for some reason the event with the blue background becomes purple and the orange one becomes transparent, leaving only the event title visible:

![Image of Yaktocat](http://i.imgur.com/FRzyfgH.png)

**Comment by entropitor** [comment]
You have to give the actual color. so `event.setColor(getContext().getResources().getColor(android.R.color.holo_orange_light));`

**Comment by ghost** [comment]
I can't believe I missed that! Sorry, that was a very silly mistake.

**Comment by entropitor** [comment]
No problem :smile:
