### ISSUE TITLE
My app uses your wonderful lib

### ISSUE THREAD

**Issue by Skyost** [Quivr/Android-Week-View#25]
Hi,
I just have to say that [my app](https://play.google.com/store/apps/details?id=fr.skyost.timetable) is using your wonderful app :heart: 
So thank you for this lib !

**Comment by entropitor** [comment]
No problem. Happy to help. This library was extended from [this library](https://github.com/alamkanak/Android-Week-View) for a very [similar app]( https://play.google.com/store/apps/details?id=be.kulapp.mobile).

If there's anything else you'd like to add, we would be glad to integrate it.

**Comment by entropitor** [comment]
Do you want to be on the readme? :smile:

**Comment by Skyost** [comment]
It would be great 😃

**Comment by entropitor** [comment]
Done
