### ISSUE TITLE
Min/Max time and time zone between two time

### ISSUE THREAD

**Issue by onurgurbuz** [Quivr/Android-Week-View#27]
Hi,

I want to ask two question. I have tried but i haven't do these. Can you help me, please? 

- My first problem is that. I want to change min/max time in a day (like 08:00-20:00).
- And my second problem I want to change time zone between time and time (like 08:15,08:30,:08:45... instead of 08:00,09:00,10:00 ...)

I need a help.
Thanks.

**Comment by jhoobergs** [comment]
Hi,

@onurgurbuz I'm sorry for answering so late, seems like I missed this issue.

For the first problem: There is still a PR about this that I will merge.
For the second problem: You have to generalise the mShowHalfHours in the WeekView class.

**Comment by onurgurbuz** [comment]
hi @jhoobergs 

thanks for your answer. i tried solve that problem, changed something in the library. i did what i want but it was complex and my time was short.

anyway thanks for your answer again.
