### ISSUE TITLE
Add Hasmap field in WeekViewEvent to allow custom data in Event object

### ISSUE THREAD

**Issue by communikein** [Quivr/Android-Week-View#28]
I think it would be a good idea to insert this kind of field because people may need to have more info for an Event than just its start, end, color, title and location, for example I really need a description and an attachments fields.

**Comment by jhoobergs** [comment]
@elia-maracani The best way to archieve this is for you to create a CustomEvent class that extends the WeekViewEvent class and overrides the necessairy methods. This solution is much cleaner than adding a map and the real OO way to do it.

**Comment by communikein** [comment]
You're right, I'm sorry I wasted your time. Don't know why I didn't think about it.
Thanks :)
