### ISSUE TITLE
All Events are cleared when creating new event at end of day

### ISSUE THREAD

**Issue by wietsebuseyne** [Quivr/Android-Week-View#29]
In Sample app:

1. Click somewhere near the end of the day
2. All events are cleared

**Comment by jhoobergs** [comment]
Hi @wietsebuseyne thanks for pointing that out.
I will try to fix it when I've got time, you may always try it yourself and make a PR.

Jesse

**Comment by wietsebuseyne** [comment]
I fixed the issue, will create a PR soon.
