### ISSUE TITLE
Input an AllDay event

### ISSUE THREAD

**Issue by Mluna97** [Quivr/Android-Week-View#33]
Hello, I have just started with this libs and I would like to input AllDay events like the normal ones, just clicking (the header) one time to make the "add-mark" appear and then once more to confirm the add event. Is that possible? I mean, I want a listener for this: 

![horas_2](https://cloud.githubusercontent.com/assets/22638938/22983751/e369b59a-f381-11e6-9d12-57269f61be42.png)

![horas](https://cloud.githubusercontent.com/assets/22638938/22983752/e3709e28-f381-11e6-97eb-3000f9c453f3.png)

Have someone any idea where can I look for in the code or how to add that listener?

Thanks in advance!

**Comment by jhoobergs** [comment]
I think you have to make some changes here: https://github.com/Quivr/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/WeekView.java#L350

Now it only allows clicks in the bottom view, I think that you can fix it by changing this if and other parts of this method

**Comment by Mluna97** [comment]
@jhoobergs Your answer helped me! I changed few ifs and the _top_ variable calculation. Also I added an allDay param in the _onEmptyViewClicked_ method. 

Thanks!! :)

**Comment by jhoobergs** [comment]
@mafra97 If you thinks it works, you may always create a pull request

**Comment by Mluna97** [comment]
Yes, I will create a pull request after testing that it has no problems! Thanks!
