### ISSUE TITLE
How to make it work inside a ScrollView or NestedScrollView?

### ISSUE THREAD

**Issue by ghost** [Quivr/Android-Week-View#36]
How to make ` WeekView` work in a `ScrollView` or `NestedScrollView`, It just works with horizontal scroll but not the vertical scroll. Have you guys any idea?

I already tried with `setNestedScrollView(true)` but nothing...

This is an awesome lib!
Thanks in advance.

**Comment by entropitor** [comment]
I don't think that's possible right now. How would you expect it to behave?

**Comment by ghost** [comment]
I was working on an app where I had to display the `WeekView ` after a form, having to put it at the end of `ScrollView `did not show all available hours, I made adjustments in size and set a start and end time and it worked for the moment .
