### ISSUE TITLE
2.0.2 setup via gradle

### ISSUE THREAD

**Issue by ezmegy** [Quivr/Android-Week-View#40]
Hey Guys,

I wanted to dig into the latest version and have the following scenario:

- I start with a blank application in Android Studio.
- Include the dependency: `compile 'com.github.quivr:android-week-view:2.0.2'`.
- And I am able to sync and compile, but the source code grabbed is some older version (possibly not even 2.0.0), so for example I do not have limit_hour feature in WeekView.java.

Should this be working or am I missing something?

Cheers

**Comment by jhoobergs** [comment]
@ezmegy With `limit_hour` feature you mean the `setLimitTime` and `setAutoLimitTime` methodes ?

**Comment by ezmegy** [comment]
@jhoobergs Yes, that's what I meant. 

But basically, the question is if anybody else is experiencing any features missing when compiling with Android studio with that specific dependency (2.0.2). This would indicate that it's not only me setting up something wrong (: -though I'm not sure what I could setup wrongly since it should work with including that single line... or not?-.

**Comment by jhoobergs** [comment]
@ezmegy I seems that those features are post 2.0.2 and not yet released.

**Comment by ezmegy** [comment]
@jhoobergs Oh, OK. 

The readme was updated to 2.0.2 and mentions minTime and maxTime in the xml customisation part, so I thought that would be ready to use. But I just saw that the latest release is 2.0.0, so probably that's what I missed before...

Any plans for a next release? (Either 2.0.2 or bigger)

(In the meantime I just downloaded the project statically so actually I don't mean to push.)

**Comment by wallforfry** [comment]
Hi ! I've got the same problem as @ezmegy, I can't use anymethod to setMinTime or use it in xml file

**Comment by jhoobergs** [comment]
@wallforfry @ezmegy Can you test with version 2.1.1 ? I haven't written anything about version 2.1.0 and 2.1.1 because the automatic prefetching of following months, is disabled in those releases and I haven't written an explanation about how you can add it yourself yet.

**Comment by ezmegy** [comment]
The gradle setup with 2.1.1 did work for me. :)

**Comment by wallforfry** [comment]
It works for me too ;)
