### ISSUE TITLE
Use String as Event Id

### ISSUE THREAD

**Issue by reilem** [Quivr/Android-Week-View#44]
Use String instead of int for Event ids. This will ease communication when fetching Custom Calendar events from device.

**Comment by shivam0x** [comment]
Just change the id in WeekView class and respective places.

**Comment by jhoobergs** [comment]
I think lines like https://github.com/Quivr/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/WeekView.java#L141 will break it then.   The easiest thing might be to create a class 'WeekViewId' which has a single property id and people can then also override that class together with the WeekView class.

**Comment by shivam0x** [comment]
Ofcourse we have to change it at all the places. In the attributes too. I'm using String instead of long by replacing it all the required places.

**Comment by jhoobergs** [comment]
Yes, but you use your own fork probably ? I would update it so people don't need to fork the repo but can just adapt it themselves by override some classes.

**Comment by udaysrinath** [comment]
Just following up on this @jhoobergs , you mentioned you are going to update it, do you have a proposed solution merged already?

**Comment by udaysrinath** [comment]
Any update on this front @jhoobergs ? Did you get a chance to get the changes for this?

**Comment by jhoobergs** [comment]
@udaysrinath I probably won't have time to do it myself in the next month. If you want to fix it yourself, just create a PR and I will find the time to review it.

**Comment by udaysrinath** [comment]
@jhoobergs Opened a PR for this, can you please review?
