### ISSUE TITLE
What is new in this fork?

### ISSUE THREAD

**Issue by ahmadalibaloch** [Quivr/Android-Week-View#45]
What are the new things that are not found in original https://github.com/alamkanak/Android-Week-View. Can you create a list?

**Comment by jhoobergs** [comment]
- All day events
- Possibility to set min and max date
- Possibility to set range of visible hours
- Possibility to show hour markers every half hour instead of every hour
- Add event by clicking on empty space
- Some bugfixes
- Quick responses on issue 😄

**Comment by ahmadalibaloch** [comment]
Great. Thanks for the info.

**Comment by entropitor** [comment]
Especially the last one is very important. The main fork is not really maintained any more. There hasn't been a commit for over a year. The last commits were all from the @quivr team (or pull requests merged by someone from the @quivr team) so we decided to fork so we have more control over releases, ...

We are very open to other contributors, in fact, it's one of the main reasons we started this fork in the first place, to have a better community around the library.

**Comment by JDunn3** [comment]
Ugh, sucks you don't have control to put that notice back on the original. It's the one that shows up when searching, I didn't notice for 2 days that there was an active fork. Just happened to see it in the commits.

**Comment by entropitor** [comment]
@JDunn3 We actually did that but @alamkanak doesn't want that (https://github.com/alamkanak/Android-Week-View/commit/2aa710e1aabdc038a47a6186107636524f73cf5c). Feel free to help us convince him, we warned him a long time ago (https://github.com/alamkanak/Android-Week-View/issues/137) but the culture didn't improve so we had to fork it so we could actively develop on this library without any hassle

**Comment by ohpoloha** [comment]
just found this from somewhere I can't remember. wish I could've found here a month ago. 

anyway, just wanted to say good job and thank you for this fork!

**Comment by ecoscootingdeveloper** [comment]
Hello,
possibility of scroll week ?
