### ISSUE TITLE
Integrating it with AgendaView

### ISSUE THREAD

**Issue by shivam0x** [Quivr/Android-Week-View#47]
Hi,
I'm integrating this lib with https://github.com/Tibolte/AgendaCalendarView .
I'm using EventBus to communicate between the events. 
So on the click on a date in the calendar I need to scroll the WeekView to that day/date and Vice-Versa. In the click event I get the Calendar and the day property also. But I'm not getting any method to change the day in WeekView class.

Also please help me with the event which gets triggered when we scroll the WeekView as I need to update the Date/Day in the Calendar for the same.

TIA

**Comment by jhoobergs** [comment]
Hi,

You can use  `setScrollListener()` to get an event every time the first visible day has changed and `goToDate()` to go to a specific date.

**Comment by shivam0x** [comment]
@jhoobergs Thanks for your reply. Yeah I was missing setScrollListener() and haven't tried goToDate().
I'll try that and close this issue.

**Comment by shivam0x** [comment]
Worked like a charm. Thanks
