### ISSUE TITLE
daysBetween method is broken

### ISSUE THREAD

**Issue by eranf91** [Quivr/Android-Week-View#49]
dateTwo: 08/09/2017 GMT+3
dateOne: 01/01/2017 GMT+2
excected result: 243
actual results: 242
When use joda time with these calendars objects I get expected result:
`Days.daysBetween(new DateTime(dateTwo), new DateTime(dateOne))`

Found in: com.alamkanak.weekview.WeekViewUtil.daysBetween()

**Comment by jhoobergs** [comment]
Do you see any issues when using the library ? This method is used internally and might actually need it to return 242.

**Comment by eranf91** [comment]
Yes, I had a bug therefore I digged in and got to the method.
In order to produce this case naturally:
The date of the device should be 08/09/2017(GMT +3), Then use method WeekView.goToDate('01/01/2017') (GMT +2) - This is actually a test case that we have.

The weekview should go to a day prior to the given date.

**Comment by jhoobergs** [comment]
Ok, can you create a PR for this and use your own test to check if it is fixed ? We currently don't have a testing framework, any suggestions ?

**Comment by jhoobergs** [comment]
@eranf91 Do you mean 01/09/2017 GMT+3 instead of 08/09/2017 GMT+3 ?

**Comment by eranf91** [comment]
1. I will open a pull a request
2. I think you should consider start work with joda time, it is a simply better library then joda time (and as far for java 8 it is come with it)
3. Thats means that you should start by adding a gradle depedency to joda time (since android is not running on JDK8)
4. I Think that the coorect method: WorkWeekUtils.daysBetween should be:
Days.daysBetween(new DateTime(dateOne), new DateTime(dateTwo)).getDays();
5. I think it is required to write  jUnits for this method since that there are to many cases to test
6. I did not mean instead, I ment that for these to values the method return invalid value

**Comment by jhoobergs** [comment]
I changed it to 
```
return (int) (((dateTwo.getTimeInMillis() + dateTwo.getTimeZone().getOffset(dateTwo.getTimeInMillis())) / (1000 * 60 * 60 * 24)) - 
                ((dateOne.getTimeInMillis() + dateOne.getTimeZone().getOffset(dateOne.getTimeInMillis())) / (1000 * 60 * 60 * 24))); 
    } 
```
for now.

The unit tests would indeed be quite helpfull.
