### ISSUE TITLE
WeekViewEvent mId needs to be generic

### ISSUE THREAD

**Issue by udaysrinath** [Quivr/Android-Week-View#59]
The ```mId``` on the WeekViewEvent needs to be a ```String``` to be generic to handle a wide range of meetingIds coming from several data sources - UUIDs, Strings or Long. With the current id being long, it makes it really hard to represent UUID using the getMostSignificantBits/getLeastSignificantBits uniquely. 

Could this id be modified to a string to be a catch-all?

**Comment by jhoobergs** [comment]
Can you check #44 and comment there?

**Comment by udaysrinath** [comment]
Thanks @jhoobergs.
