### ISSUE TITLE
onMonthChange firing late previous month (left scroll)

### ISSUE THREAD

**Issue by udaysrinath** [Quivr/Android-Week-View#70]
@jhoobergs Any thoughts why the MonthChangeListener would not fire on scrolling left to a previous month? Works fine on next month.

Here is how the listeners are setup, similar to the sample app:
```
        mWeekView.setOnEventClickListener(this);
        mWeekView.setMonthChangeListener(this);
        mWeekView.setEventLongPressListener(this);
        mWeekView.setEmptyViewLongPressListener(this);
        mWeekView.setEmptyViewClickListener(this);
        mWeekView.setAddEventClickListener(this);
```

**Comment by udaysrinath** [comment]
Ok figured out the issue, on the left scroll (prev month), the event fires when crossing midway in the month (~ 15th), ideally should fire sooner more like the end of the month. In the case of right scroll (next month), event fires when cross the 1st of the month.

Any reason to keep this current behavior on the previous month? Can we change that?

**Comment by jhoobergs** [comment]
I think that the event fires on the 15th, for the next/previous month, not for the current month.

@entropitor I think you know this better

**Comment by entropitor** [comment]
@udaysrinath This is implemented like this to reduce the number of times the requests are fired, otherwise there are a lot of requests if you are on the edge of a month

**Comment by udaysrinath** [comment]
That was my thinking as well, thanks for confirming @entropitor, @jhoobergs . Agree that there is a higher chance of looking for future events than the past ones. Closing this as by design!
