### ISSUE TITLE
can I hide title?

### ISSUE THREAD

**Issue by ohpoloha** [Quivr/Android-Week-View#75]
I'm doing `noOfVisibleDays=1`, and I'll have date in ToolBar. therefore, repeating the date again in title(top) is kinda redundant. Is there any way I can hide that? Thanks

**Comment by jhoobergs** [comment]
Currently it's not possible, but check https://github.com/Quivr/Android-Week-View/issues/71#issuecomment-359525084

**Comment by ohpoloha** [comment]
Thanks for the tips!
