### ISSUE TITLE
One more question about NewEventTimeResolutionInMinutes 

### ISSUE THREAD

**Issue by empeusz** [Quivr/Android-Week-View#80]
Is it possible to set or modify NewEventTimeResolutionInMinutes so it can display hours, half-hours and 15min's as shown on attached png? 

![timeline](https://user-images.githubusercontent.com/31664066/35923003-60166b9a-0c1f-11e8-97aa-66bfbb663d02.png)

**Comment by jhoobergs** [comment]
@empeusz Currently not.

**Comment by empeusz** [comment]
@jhoobergs I see... can we move this one to pull request section then ? Or should I create a new one ?

**Comment by jhoobergs** [comment]
@empeusz You should create a PR yourself with the fixes.

**Comment by empeusz** [comment]
Finally I was able to change it by modyfing `public void setupDateTimeInterpreter` and Overriding 

`@Override`
            `public String interpretTime(int hour, int minutes) {`
                `String strMinutes = String.format("%02d", minutes);`
               ` if (minutes > 0) {`
                  `  return  strMinutes;`
         `       }`
           `     return hour + ":" + strMinutes;`
          `  }});`

May come in handy for other users ;)
