### ISSUE TITLE
Question: how to focus on a specific time of day?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Quivr/Android-Week-View#99]
I know it's possible to go to a specific date, but what about time?

I need that initially, we focus on current time of the day, so that we could see some above, and some below . Say 10% above vs 90% below. 

Similar to what we have on Google Calendar:

![image](https://user-images.githubusercontent.com/5357526/39756264-85a2950c-52d1-11e8-9fb1-058e2f64944e.png)

Is it possible? If so, how?

**Comment by AndroidDeveloperLB** [comment]
Never mind. It's called: `goToHour` . Seems to work fine too.

**Comment by SkyleKayma** [comment]
I have an answer to "how to focus on a specific time range of day?" (like 08:00 to 20:00, without cutting the rest), I have work on something, that need to be improved : 

`public float getWeekViewHeightWithoutDateNorHour() {
        return (float)this.getHeight() - (this.mHeaderHeight + (float)(this.mHeaderRowPadding * 2) + this.mHeaderMarginBottom);
 }`

That returns the Height of the weekView, then do something like : 

`private var NUMBER_OF_HOURS_TO_SHOW: Double = 12.0`

`weekView.hourHeight != (weekView.weekViewHeightWithoutDateNorHour / NUMBER_OF_HOURS_TO_SHOW).toInt()`

**Comment by AndroidDeveloperLB** [comment]
@SkyleKayma Well this could also be nice.

**Comment by Mluna97** [comment]
@SkyleKayma where would you set the hourHeight in your example?
